name: Update README Daily

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    # Ensure the workflow doesn't run for the GitHub Actions bot or for merge commits
    if: |
      github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, 'Merge pull request')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Rebase from main
        run: |
          git checkout main
          git pull
          git branch -D automated-updates || true  # Delete the branch if it exists, ignore if it doesn't
          git checkout -b automated-updates

      - name: Update README.md
        run: |
          days_since_epoch=$((`date +%s`/86400))
          random_number=$(( RANDOM % 100 + 1 ))
          sed -i "s/\(&v=\)[0-9]*/\1$days_since_epoch/g" README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update &v value in README.md"
            git push origin automated-updates
          fi

      - name: Install GitHub CLI
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.3.0/gh_2.3.0_linux_amd64.tar.gz -o gh.tar.gz
          tar xvf gh.tar.gz
          sudo install gh_2.3.0_linux_amd64/bin/gh /usr/local/bin/

      - name: Create Pull Request and Merge
        run: |
          gh auth login --with-token <<< "${{ secrets.README }}"
          PR_URL=$(gh pr create --base main --head automated-updates --title "Update &v value in README.md" --body "Automated update of &v value.")
          gh pr merge $(basename $PR_URL) --merge

      - name: Delete branch on failure
        if: failure()
        run: |
          if git show-ref --verify --quiet refs/heads/automated-updates; then
              git push origin --delete automated-updates
          else
              echo "Branch automated-updates does not exist. Skipping deletion."
          fi
