name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # This will run the job every day at midnight

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README.md
      run: |
        days_since_epoch=$((`date +%s`/86400))
        sed -i "s/\(&v=\)[0-9]*/\1$days_since_epoch/g" README.md

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update &v value in README.md"
        git push
