name: Update README Daily

# on:
#   schedule:
#     - cron: '55 16 * * *'
on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Rebase from main
        run: |
          git checkout main
          git pull
          git branch -D automated-updates || true  # Delete the branch if it exists, ignore if it doesn't
          git checkout -b automated-updates

      - name: Update README.md
        run: |
          days_since_epoch=$((`date +%s`/86400))
          sed -i "s/\(&v=\)[0-9]*/\1$days_since_epoch/g" README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update &v value in README.md"
          git push origin automated-updates

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Create Pull Request and Merge
        run: |
          gh auth login --with-token <<< "${{ secrets.README }}"
          PR_URL=$(gh pr create --base main --head automated-updates --title "Update &v value in README.md" --body "Automated update of &v value.")
          gh pr merge $(basename $PR_URL) --merge
